### PR TITLE
Fix/date serialization

### PR DESCRIPTION
**Pull request by rneher**
## Related issues and PRs

#409 

## Description
This adds a simple (brittle) conversion from the simulation.timeRange date  strings '%Y-%m-%d' to a  date object and timestamp. This is most likely not how this should work. But it fixes the bug. 

## Impacted Areas in the application
conversion of the state to object that goes into serialization.

### CODE REVIEW

**Comment by rneher** [comment]
@dkozar -- there is likely a reason why this isn't the road you chose. I was largely curious why this happened and wondered whether I could fix it...

**Comment by rneher** [comment]
I saw the other discussion -- feel free to disregard...

**Comment by dkozar** [comment]
The readon was that I assumed this is a bug, which needs to be fixed at the source. Because vetting the string instead of date looks like an error.

So I wrote this as a throwaway code, with a goal to temporarily mitigate the problem (so we can merge my PR) until we fix at at the source. Your change is good, but it masks the problem to the extent that it stops being the problem - and we’ll probably never address it at the source. :)

**Comment by rneher** [comment]
yeah, I just papered the problem over. We definitely need to look into the fact why dates are pulled out differently from different date pickers.

**Comment by gj262** [comment]
Looks good to me. Those string dates are coming from scenarios.json and need to be handled.

**Pull request merged**
