### PR TITLE
Reintegrate the data into the main repo

### PR DESCRIPTION
**Pull request by nnoll**
## Related issues and PRs

Addresses Issue #282

## Description

Reintegrate the data repository while preserving the git history of the original repository. 

## Impacted Areas in the application

The entire data directory is now a directory and not a submodule.

## Testing

Check if it still builds.

### CODE REVIEW

**Comment by noleti** [comment]
Running on a fresh clone I tested all the `generate_data.py` calls. All except `--output-scenarios` work. The latter fails with `No such file or directory: '../covid19_scenarios/src/assets/data/country_age_distribution.json'`, although from the directory where I run there is such a file

> $ ls ../src/assets/data/country_age_distribution.json 
> ../src/assets/data/country_age_distribution.json

Is that a known issue?

**Comment by rneher** [comment]
there will be a few more chores and improvements. For examples these numbers
https://github.com/neherlab/covid19_scenarios/blob/chore/reintegrate-data-repo/covid19_scenarios_data/scripts/model.py#L95
should come straight from here:
https://github.com/neherlab/covid19_scenarios/blob/chore/reintegrate-data-repo/src/assets/data/severityData.json

**Comment by nnoll** [comment]
@noleti this was a vestige of the seperated repos. Should be fixed now, along with less name redundancy.

**Comment by nnoll** [comment]
@rneher yes I know. I was saving these for a separate PR that will modify all python classes to pull from a unified schema

**Comment by rneher** [comment]
lets merge this and improve on it later

**Pull request merged**
