### PR TITLE
Update faq.mdx

### PR DESCRIPTION
**Pull request by samanthahamilton**
Issue #687, continued

## Related issues and PRs

 - Continuing to address Issue 687: this focus addresses /faq page 

## Description

- Optimizing readability, editing, focus on "blog-like" language
- Attached is .docx file of explanations and further detail of changes

## Impacted Areas in the application

- /faq page

## Testing

- n/a

[neherlabCOVID19_faq_SHamilton_3Aug2020.docx](https://github.com/neherlab/covid19_scenarios/files/5016820/neherlabCOVID19_faq_SHamilton_3Aug2020.docx)

### CODE REVIEW

**Comment by samanthahamilton** [comment]
Hi, @ivan-aksamentov 

I just wanted to touch base about continuing Issue #687 (goals to: make it more optimized for reading; improve sentence structure and paragraph). After finished /about, I've done edits on the text file for /faq (attached in this PR). The PR says, "some checks were not successful," and I was wondering if there was anything else you needed me to do?

Thanks! Cheers,
Sam.

**Comment by ivan-aksamentov** [comment]
@samanthahamilton Thanks l lot! Richard @rneher  might not be available for a few days, but as soon as he's back, I'll ask him to review the changes.

Regarding the "Some checks were not successful" message, it was due to a merge conflict (There was also a message "This branch has conflicts that must be resolved" and `faq.mdx` in the list of conflicted files) below. The reason is that we did a little reorganization (in #737) and `faq.mdx` was renamed and moved to another folder between the time when you branched off master and the time when you submitted this pull request. In this situation, GitHub does not know how to combine the two changes and asks for manual intervention.

In order to resolve the conflict, I merged the current "origin/master" into your branch and pushed. So your changes have successfully migrated to the new file location - `src/components/Faq/FaqContent.mdx `. But that also means that there are now new changes in this file since you last saw it. Could you please pull your updated branch and review the file once again? As always, you can see how it will look on the actual website by using the link provided by Vercel bot above: https://covid19-scenarios-git-fork-samanthahamilton-improve-styling.neherlab.vercel.app/

In the future, it is easy to avoid merge conflicts - just make sure you pull the latest master before branching off. And if master gets updated after you branch off, then just merge the fresh master from the origin into your branch (just like I did just now). I know that the git and GitHub may be tricky at times, so let me know whenever you need some help with it.

Also, if you want to contribute more, whether in editing, in code, or otherwise, don't hesitate to open multiple concurrent pull requests.

I can send you an invite you to our Slack channel, so that you could communicate with the team and other contributors more directly. If you are interested, please send me a private message on Spectrum with your email address. My username is [ivan-aksamentov](https://spectrum.chat/users/ivan-aksamentov).

**Comment by samanthahamilton** [comment]
Hi Ivan,

Thank you so much for your help. GitHub certainly presents a unique learning curve. 

I appreciate that you have merged the current “origin/master” into my branch and pushed these changes. I’m trying to open the updated branch on my desktop. Unfortunately, the new file location `src/components/Faq/FaqContent.mdx` does not appear. 

I have tried `cd`:

`git remote -v` [to confirm the origin and upstream are correct]
`git checkout master`
`git reset --hard origin/master`
`git pull --rebase upstream master`
`git merge master`

In all cases, I receive an error message saying `error: invalid path 'data/case-counts/india/IND-Telangana***.tsv'`

Am I missing something? Should I delete my fork and start over? I love contributing, but I’m still trying to learn the GitHub workflow, and I hope to be better at merging any upstream commits to my fork/branches in the future--my worry is messing up other people’s projects unintentionally!

**Comment by ivan-aksamentov** [comment]
@samanthahamilton 
 > Should I delete my fork and start over?
Looks like there's something with completely unrelated files.
As popular joke goes, just delete (or better rename) the local repository on your computer and clone it again. Don't delete the fork on GitHub.
https://xkcd.com/1597/
:)

You may also take a look at [GitKraken](https://www.gitkraken.com/git-client). It's a good UI-based client for git. Might help you to better visualize the tree, the problems and provides better error messages. You can combine command line tools and GitKraken for the best effect.

Invited you to slack. Say hello :wave:

**Comment by samanthahamilton** [comment]
Hi Ivan. Thanks again for _all_ your help!

> Could you please pull your updated branch and review the file once again? 

There were a few small changes to make with the new file (which was successfully pulled!).

> What operating system and command line shell you are using? Also what is your git --version?

I use Windows 10, and the built-in command line. My husband says he also has Power Shell and Comeyo, if I need. And the `git --version` is 2.28.0

Cheers, Sam.

**Comment by rneher** [comment]
this looks great. Thanks so much @samanthahamilton!

**Pull request merged**
