### PR TITLE
#19/add timeseries tests

### PR DESCRIPTION
**Pull request by abrie**
## Description

This PR adds granular unit tests for all the functions exported by the `src/utils/TimeSeries.ts` module.

## Related issues

#19 

## Impacted Areas in the application

This impacts the unit testing only.

## Testing

Run 'yarn test' to verify.

### CODE REVIEW

**Comment by ivan-aksamentov** [comment]
@rneher @nnoll Could you please review this test suite? In particular, whether the inputs and outputs are within your expectations. Are there additional test cases you might suggest?

**Comment by ivan-aksamentov** [comment]
@abrie Thanks! I will let our algorithm specialists to review.

**Comment by nnoll** [comment]
This looks great! Thanks for your contribution.

There are two major places the updateTimeSeries function is used, either when the number of points on the mitigation curve changes (which is now tested) or when the date range (tMin and tMax) is updated. The later use case is not tested under the current suite. Once its added I think we should merge.

**Comment by ivan-aksamentov** [comment]
@abrie @nnoll I'll merge as is, but @abrie feel free to push more, here or in a separate PR.

**Pull request merged**
