### PR TITLE
Adds internal states to exposed class

### PR DESCRIPTION
**Pull request by nnoll**
Modifies the underlying algorithm to allow for a more realistic latency distribution as per Issue #182 . This qualitatively changes the predictions so we should look at this with critical eyes. 

Note, I had to break a bit of the types that have been so nicely set up. This probably needs the attention of someone more fluent in typescript to make the linter happy.

Also includes some refactoring of the UserResult that should decouple the simulation data structure and that used for plotting.

### CODE REVIEW

**Comment by rneher** [comment]
This looks very good. I would suggest to remove the hard coded `3` in various places. Also the terminology could use revision. `newInfectious` is only a good name for the very last exposed category. Why not call it something like `exposedFluxOut`. While you are at it, maybe change `incubationTime` to `latency`?

**Comment by nnoll** [comment]
@ivan-aksamentov what needs to be done to get this merged? I'd like to update the model before this branch desyncs too much.

**Comment by ivan-aksamentov** [comment]
@nnoll It needs to mergeable but also it is desireable for it to be functional. The deployed version crashes on Run. I'll see what can be done.

**Comment by ivan-aksamentov** [comment]
@nnoll In this commit, where you merged master into the feature branch:
https://github.com/neherlab/covid19_scenarios/commit/711b5a4603272f8ed47791dfb0a9e2d2468c0b02
the number formatting/humanization was not merged correctly.
I added missing variables, so at least it runs now, but I am still not sure if there are other problems.
I'll merge and then we can hopefully fix if somethings remains. And tests of course.

**Comment by ivan-aksamentov** [comment]
I close this dues to errors in merges. I rewound all the non-erroneous commits in #221 and will merge it.

**Pull request closed without merging**
