### PR TITLE
[WIP] Improving SEO meta tags

### PR DESCRIPTION
**Pull request by thoo1**
Doing this WIP so I can leverage existing CI/CD pipeline to test as if this was in prod

## Related issues and PRs
 - Contributes to 105 (first time looking into SEO feel free to give suggestions on what I should look to do)
- for example localizing tags? Do I need to do this?

## Description
- aims to improve SEO
- was thinking of use react-helmet but didn't want to setup SSR as I'm not sure what would break

## Impacted Areas in the application
- index.ejs
- .env
- webpack.client.babel.ts

## Testing
- test with facebook https://developers.facebook.com/tools/debug/
- and other social media

### CODE REVIEW

**Comment by ivan-aksamentov** [comment]
@thoo1 Looks good.

Could you please rebase on latest master? We've introduced some limitations on CI and the old eslint errors (now fixed) fail the checks.

Could you please also make a screenshot of the results in the Facebook debug tool?

Feel free to look further into the similar Twitter integration (that's what we use mostly for sharing the updates).

**Comment by thoo1** [comment]
sure, also i noticed Zeit Now is not deploying my changes, maybe because I pushed too much :( could I get authorization to deploy? Thanks

**Comment by ivan-aksamentov** [comment]
@thoo1 Oh, turns out they require authorization if PR contains changes in `now.json` . I just authorized this. There are also errors in Travis, but ignore this for now.
Rebase on master and keep going :)

**Comment by thoo1** [comment]
@ivan-aksamentov if you could authorize one more time :P

**Comment by ivan-aksamentov** [comment]
@thoo1 Done!

**Comment by ivan-aksamentov** [comment]
Looks like it works fine, so I'll merge. Feel free to add stuff in a new PR.

**Pull request merged**
