### PR TITLE
Fix e2e tests + add navigation landing e2e tests

### PR DESCRIPTION
**Pull request by kioviensis**
## Related issues and PRs
#287 
also, I have added some new tests which cover interaction with LandingPage

## Description
Fix e2e tests and refactored some code that might cause distraction once again

## Impacted Areas in the application
e2e tests and charts

## Testing
Run e2e tests

### CODE REVIEW

**Comment by maktarsis** [comment]
I apologize if there is some refactoring here, but there were reasons for this

some files were not processed by the linter (and this resulted in the fact that the landing page almost completely corresponded)

some files contained unused or wasted declarations

**Review by ivan-aksamentov — CHANGES_REQUESTED** [review]
@maktarsis Thanks Max,

Unfortunately the app seems to be crashing now on Run when Polish locale is selected. I checked on the deployed version above. Could you please investigate?

For new contributors, I would prefer more focused PRs, to be honest. This one tries to fix everything, Really hard to review. And as you see, it introduces or exposes some bug, and I cannot even find why.

How about we do e2e fixes separately and then some focused 1-2 files at a time refactors afterwards?
That'd be fantastic!

Try to not format the code for now.  I know it's ugly, but we can do this later in a "format-only" PRs, to make sure nothing snicks into the fat diff. I promise you, in a few days we will be having a clean lint and coding style :)

Don't hesitate to push here or to open another one, whatever is more convenient for you.

**Comment by maktarsis** [comment]
@ivan-aksamentov sounds good

**Comment by maktarsis** [comment]
@ivan-aksamentov it's ready to be reviewed and merged

**Comment by maktarsis** [comment]
that's not cool

- ignoring
- all my changes were copied by other developers

ok, I don't want to take part in this

**Comment by maktarsis** [comment]
that's not cool

- ignoring
- all my changes were copied by other developers

ok, I don't want to take part in this

**Pull request closed without merging**
