### PR TITLE
Add Finnish string translations to the project

### PR DESCRIPTION
**Pull request by juhalehtonen**
## Description
This PR adds Finnish string translations to the project's i18n resources.

## Impacted Areas in the application
This PR adds Finnish translations to the available i18n resources. Thanks to @ivan-aksamentov 's contribution, this PR also adds the Finnish language as a dropdown option in the language selector.

## Testing
Testing should be done by changing the language to Finnish and viewing through all UI elements of the application.

### CODE REVIEW

**Comment by ivan-aksamentov** [comment]
@juhalehtonen Hi Juha,

Thanks so much for the contribution!

If you don't mind, I added Finnish language to the dropdown menu.

I unfortunately don't posses any Finnish language skills. If you have a minute, please verify that everything works as intended (you can use Vercel preview link above). And if it looks good, let me know and we will merge and release this.

**Comment by juhalehtonen** [comment]
Hello @ivan-aksamentov !

Thank you so much for your input. I'm a bit busy this weekend, but I'll definitely check everything through and will update the PR accordingly. 

There were a couple of strings still missing, and I still want to double-check that my use of terminology matches what I've seen in Finnish media and other outlets for consistency and clarity. Now that I had a look at the vercel app with your additions, the increased context allows me to see that I can tweak a couple of strings to feel more natural in their usage.

I'll also have a look at the number formatting as per your request :)

**Comment by juhalehtonen** [comment]
I've added and improved translations, and also verified that the number formatting makes sense for a Finnish user. I'm still not 100% happy with the texts, and will create at least one more commit before changing the PR draft status. Getting close though :) 

As a sidenote: while verifying and testing my translations, I noticed that not every UI string seemed to be present on the english language base file (as in, not every string seemed to be translatable). I didn't see an existing issue about this, so perhaps I'm just missing something.

**Comment by juhalehtonen** [comment]
I've added some more missing translations and updated a few strings to better match the intended purpose and context. I changed the status of this PR from draft to ready, allowing it to be merged.

**Comment by ivan-aksamentov** [comment]
Thanks a lot @juhalehtonen ! Merging this.

Indeed, the i18next setup seems to be currently buggy. I created an issue for that: #808

**Pull request merged**
