### PR TITLE
fix issue#474: the language switcher is cut off by the main content

### PR DESCRIPTION
**Pull request by guandiyiyi**
## Related issues and PRs
issue #474 
 - 

## Description
The language dropdown is cut off by the main content, because it's attached to navigation container, add attribute positionFixed to fix the menu position.

## Impacted Areas in the application
NavigationBar.tsx
LanguageSwitcher.tsx

## Testing
open the application, click the language switcher, noticed the dropdown is shown as expected.
image

### CODE REVIEW

**Comment by rneher** [comment]
yes, we disabled this for the time being since there are so many strings that are untranslated that the different languages are not very useful.

**Comment by guandiyiyi** [comment]
Ah, ok, I saw this issue tagged as Important such that I picked it up, also I have another PR fixing translation of date picker. You can take a look as well.

**Comment by whiver** [comment]
So is it a real bug or is it expected? Because this I'm working on improving the translation process in #494, so this would be a good opportunity to improve the translations, if we re-enabled them 😁

**Comment by ivan-aksamentov** [comment]
@whiver This is a chicken and the egg kind of problem. We cannot enable i18n before there is enough translation. And we cannot ave these translations before people come and translate.

Also we tend to change strings all the time. Automation should help, hopefully.

**Pull request merged**
