### PR TITLE
Scenarios set by a JSON of individualized presets

### PR DESCRIPTION
**Pull request by nnoll**
## Related issues and PRs

Related to PR #155.
Related to Issue #120 

Required changes to the data repository have been made (the json is exported).
## Description

Now that case count data is widely available for many regions, we can automate the construction of **some** default parameters for scenarios by fitting the available data. This *should* increase the usability of the model.

Because epidemics initiated at different times in different locations, experienced different growth rates, this requires restructuring how scenarios are dispatched by the user. Instead of the combinatorial manner in which a scenario is constructed now, we adopt a simpler strategy which allows the user to specify the region they are interested in and the scenario is filled in accordingly.

## Impacted Areas in the application

Scenario dispatch touches many aspects of the app's frontend.

### CODE REVIEW

**Comment by nnoll** [comment]
So I'll leave this for the day. If anyone wants to check it out, the repo doesn't have a needed file assets/data/scenarios/scenario.json. This is generated from the data repo (see the README on how to generate). The fits are currently off so more tweaking needs to occur. So far everything appears to work, but would appreciate some third party testing.

**Comment by gj262** [comment]
hey @nnoll I'll try to resolve these conflicts

**Comment by gj262** [comment]
I'm trying to generate `scenarios.json` so that I can run this, but I get:

```
Stored data for 3890 regions to json
Generating population json
Generating scenario json
Traceback (most recent call last):
  File "covid19_scenarios_data/generate_data.py", line 63, in <module>
    scenarios.generate(args.output_scenarios)
  File "/Users/gavin/work/covid19_scenarios/covid19_scenarios_data/scripts/scenarios.py", line 160, in generate
    fit_all_case_data()
  File "/Users/gavin/work/covid19_scenarios/covid19_scenarios_data/scripts/scenarios.py", line 152, in fit_all_case_data
    fit = Params.fit(data)
  File "/Users/gavin/work/covid19_scenarios/covid19_scenarios_data/scripts/scenarios.py", line 66, in fit
    data = np.array([ ([to_ms(dp['time']), dp['cases'] or np.nan, dp['deaths'] or np.nan]) for dp in pop ])
  File "/Users/gavin/work/covid19_scenarios/covid19_scenarios_data/scripts/scenarios.py", line 66, in <listcomp>
    data = np.array([ ([to_ms(dp['time']), dp['cases'] or np.nan, dp['deaths'] or np.nan]) for dp in pop ])
KeyError: 'deaths'```

**Comment by ivan-aksamentov** [comment]
@gj262 @nnoll  Could it be because the submodule is not up to date?

**Comment by gj262** [comment]
> @gj262 @nnoll Could it be because the submodule is not up to date?

This is how I 'pulled' the submodule FWIW:
`git submodule update --init --recursive`
(while the feature branch was checked out)

**Comment by ivan-aksamentov** [comment]
@gj262 I mean Nick might have forget to update the submodule in this branch. Try to checkout master inside it.

**Comment by ivan-aksamentov** [comment]
@gj262  Another hypothesis is that script is expected to be executed from a particular directory.

**Comment by nnoll** [comment]
The script is intended to be run in a directory structure 
- covid19_scenarios
- covid19_scenarios_data
...

Shall I commit a json to make this easier to test?

**Comment by nnoll** [comment]
As in, both repos are at the same level. This is to mimic Richard's layout (I presume) as this is ultimately what the script was written for

**Comment by gj262** [comment]
Ivans suggestion worked for me. i.e. updating to the latest master.

**Comment by gj262** [comment]
Ok. On @ivan-aksamentov's request, I reviewed the code and took a look for regressions and while I can't say that I fully grok the feature, the changes LGTM. Someone just needs to figure out a zeit.co deployment model and this will be mergeable.

**Comment by nnoll** [comment]
Well if it passes people's checks I think we should merge. The fits are subpar and will be improved soon but I think they are about on the same qualitative agreement as the current approach.

**Pull request merged**
