### PR TITLE
Update data

### PR DESCRIPTION
**Pull request by rneher**
## Description
update data and make all path relative to base of the data directory

## Impacted Areas in the application
update data. only the tsv

### CODE REVIEW

**Comment by rneher** [comment]
the case count json could now be generated on build with 
`python data/generate_data.py --output-cases src/assets/data/case_counts.json` in split seconds. 
should we add this json to gitignore and generate it? But this would require a python env

**Comment by nnoll** [comment]
A python env is probably needed. It would resolve Issue #342

**Comment by nnoll** [comment]
I'm also for ignoring case-counts.json (and scenario.json while we are at it) to reduce diff noise.

**Comment by rneher** [comment]
scenarios take a while to compute and don't need recalc on a daily basis. but I agree in principle.

**Comment by nnoll** [comment]
Merge this when you are ready Richard. I can include a Python environment when I finish the json schema overhaul

**Comment by rneher** [comment]
I updated the scenario json for now. We can decide two to generate them later.

**Pull request closed without merging**
