### PR TITLE
#383/Apply fluid grid layout to mitigation interval UI.

### PR DESCRIPTION
**Pull request by abrie**
## Related issues and PRs

#383 

## Description

An attempt at a "one true fix" for styling of the mitigation intervals. Uses Reactstrap/Bootstrap to satisfy the "Should be pretty 👩‍🎨 ✨" requirement.

## Impacted Areas in the application

UI of Mitigation Interval editor

## Testing

Run a dev server, open the app, try various browser window widths.

### CODE REVIEW

**Comment by ivan-aksamentov** [comment]
Hey, @abrie you seem to be closing your PRs recently, and some of them are really valuable.

For personal reasons, I am not able to review a lot of PRs right now, and our scientists not always have time and knowledge to do that.

We are gathering our most valuable contributors and are giving them write access to the repo, so that they can be more autonomous. Do you want to join the effort? Then send me a PM with your email on Spectrum:
https://spectrum.chat/users/ivan-aksamentov
and I will invite you to our Slack channel.

**Comment by abrie** [comment]
Thanks @ivan-aksamentov. I closed the PR's out of diffidence.

**Comment by ivan-aksamentov** [comment]
@abrie This looks great!

 - [ ] Do you see a way to keep the headings of the table (like on master) or labels to the left of each of the fields (similar to main form)?
 - [ ] Maybe there is a way to also fit the help buttons line in main form?
 - [ ] We might wrap each element in either a div with border or with separators at the bottom. Right now the two items fuse together and it is hard to see where one ends and another starts. 
 - [ ] We may also tint item's background slightly using interval's color (we might need to generate some more colorful default ones)

The actual labels can be changed to shorter synonymous ones, for example "name", "dates", "effect".

We mostly care about desktop (1080p and above), and laptop layouts (HiDPI, MDPI). Maybe iPad. 

Mobile can omit the help buttons and/or labels/headings. I think bootstrap's `d-*` classes should do the trick.

**Comment by abrie** [comment]
@ivan-aksamentov It's been a while since I've looked at this PR. I just tried to rebase with master and encountered challenging conflicts. Will take a look and see what can be salvaged.

Also found that the current master deployment has some issues:
image

**Comment by ivan-aksamentov** [comment]
@abrie Yes, mobile is currently somewhat broken, because it's a `<table/>` and it is not responsive at all. The tradeoff is making it more informative for desktop vs pretty on mobile and the decision is never in favor of mobile. So, that's what we got :)

I'd appreciate if you  could take a look. You can override whatever is on the master branch, and just continue your line of work, while also adding the labels/headings somehow as described in the above message.

**Comment by abrie** [comment]
@ivan-aksamentov After some experimentation, I've been unable to find a way to include text labels next to the fields. There just isn't enough space. However, with a slightly different arrangement, there is enough room for the help button sans text:

image

image

**Comment by ivan-aksamentov** [comment]
@abrie I ended up with another flexbox-based custom solution (now on master). Again, mostly optimized for desktop.

Thanks for the efforts!

**Pull request closed without merging**
