### PR TITLE
Lowered euler step size

### PR DESCRIPTION
**Pull request by nnoll**
The integration of the ODE should be more accurate.

## Related issues and PRs

None

## Description

Changed the step size/day. Removed hard-coded instances of this assumption.

## Impacted Areas in the application

The ODE integration and the line plot which assumed a 4 times/day sampling.

## Testing

Performance could be impacted. Please test.

### CODE REVIEW

**Comment by ivan-aksamentov** [comment]
@nnoll I did not notice anything. Do we do more looping now? Should I look at something specific?

**Comment by ivan-aksamentov** [comment]
Do you want me to add a separate collapsible card for Advanced params?

**Comment by nnoll** [comment]
I personally don't think we should expose this parameter. It is a technical detail at best and could go away in the future if we change how we integrate the ODEs. I mostly wanted you to test if the performance noticeably changed. I'm on a relatively beefy desktop so I'm not the ideal tester.

**Comment by rneher** [comment]
I don't notice a change. We are now doing 5x more compute. this suggests that solving the ODE really isn't the issue. I suppose all the other linting changes are of the good kind?

**Comment by nnoll** [comment]
@rneher. We had a bit of overhead that I removed that caused some noticeable. We would append all time-points to one large array, and then filter these out for plotting. It made more sense to just keep track of the current state of the ODE and then append the result every day. Less useless computation.

**Comment by rneher** [comment]
Yes, filtering this down right away is good.

**Pull request merged**
