### PR TITLE
Feat/print pdf

### PR DESCRIPTION
**Pull request by brunorzn**
## Related issues and PRs

 Contributes to https://github.com/neherlab/covid19_scenarios/issues/110

## Description

This pull request uses mostly CSS rules to prevent things to be printed out - or exported as a PDF using the browser dialog.

It has nothing to do with what has been already done in the open PRs. It doesn't load any extra library or anything, it just uses CSS.

## Impacted Areas in the application

The only thing that is impacted outside of specific-to-print is the export dialog : I've added a "print" button there.

## Testing

Run a simulation > Export > Print.

I've tested it on chrome and it works very well.
I have tested it on Firefox (Mac OS) and only the first page would be exported. Maybe a problem with some META Tags ? I've read that somewhere, but I can't find it anymore. I don't know, I didn't have time to fix this, but let's hope it will be easy.

Example (printed from chrome) : 
[COVID-19 Scenarios.pdf](https://github.com/neherlab/covid19_scenarios/files/4447469/COVID-19.Scenarios.pdf)

### CODE REVIEW

**Comment by brunorzn** [comment]
Update :

it doesn't work with safari either (which displays two columns)
and it's a bit ugly on Windows

I'm probably just too bad with CSS.

I still think it's a good approach, and I hope things can be fixed quickly, at least on chrome for every platform. 

I'm letting this PR open, so you can try things out on the preview.

**Comment by gj262** [comment]
In case anyone didn't know this (me for instance):
https://css-tricks.com/can-you-view-print-stylesheets-applied-directly-in-the-browser/

**Comment by ivan-aksamentov** [comment]
@brunorzn Good job!

The layout is still quite janky, but this can be improved, I think. Firefox/Safari would be much more challenging.

However, my primary concern is whether the contents of this PDF is of any use.

Our main results are the numbers such as deaths, number if patents in ICU, ICU overflow in the given time. The essence of the app is in these numbers. That's what we need to communicate.
However, we don't explicitly show them in the app. User have to hover the plot to see these numbers in a wonky and jumpy tooltip with fields constantly blinking on and off ( #233 ). In PDF it's even worse - no tooltips - numbers cannot be seen. In the end, there are 5 pages with almost no useful results.

We should find a way to communicate our results more clearly. Maybe we need to figure some sort of a summary table? Maybe print-only for now?

The challenge is to find an appropriate visual representation for the time-series. Should we chose a fixed step? Should user decide?

cc @rneher @nnoll @noleti @gj262 @abrie

**Comment by rneher** [comment]
yes, it works reasonably well on chrome, but on firefox only the preamble is present.

**Comment by noleti** [comment]
I tested on Linux/Firefox 74.0.1, and I also just get the disclaimer page 
[example(https://github.com/neherlab/covid19_scenarios/files/4448990/covid.pdf)

**Comment by brunorzn** [comment]
I'm working on fixing layouts for both Firefox and Chrome (not mac).

Once this is done, we can implement printed-only figures.

**Comment by brunorzn** [comment]
Update:

exports now works for both Chrome / Firefox but the process is a bit different.
in the "export" dialog, you can generate a preview, which will clean the dom up before printing.

that way, it's much easier to have control over what's being printed or not (no more columns, floats, etc).

I've also added labels to some diagrams.

[CHROME.pdf](https://github.com/neherlab/covid19_scenarios/files/4451167/CHROME.pdf)
[FIREFOX.pdf](https://github.com/neherlab/covid19_scenarios/files/4451169/FIREFOX.pdf)

**Comment by brunorzn** [comment]
updated, with table.

[withTable.pdf](https://github.com/neherlab/covid19_scenarios/files/4451488/withTable.pdf)

**Pull request merged**
