### PR TITLE
Autorun scenario on severity change

### LINKED ISSUE #200: IMPORTANT: Changes in severity table do not trigger autorun
# 🐛 Bug Report

When autorun checkbox is enabled, changes in the form or in mitigation graph correctly trigger autorun. However, when values in severity table are edited the run not triggered. The "Run" button is also disabled in this case, so there is no way to manually trigger rerun.

## How to reproduce

Steps to reproduce the issue:

 1. Open the application in a browser

 2. Check autorun checkbox

 3. Expand severity table card and edit values in the table. Observe no changes are in the plot.

## 😯 Current Behavior

Changes in severity table do not trigger autorun

## 🤔 Expected Behavior

Changes in severity table trigger autorun

## 🌍 Your Environment

Any

## Related:

 - https://github.com/neherlab/covid19_scenarios/pull/170

cc: @rcbevans Rich, you know more than anyone else about this feature. Could you please take a look?

### PR DESCRIPTION
**Pull request by rcbevans**
## Related issues and PRs

Fixes #200 

## Description

This PR updates the debounced autorunning of the scenario, when checked, to ensure that autorun is triggered on severity table changes.

## Impacted Areas in the application

Scenario autorun.

## Testing

Ensure autorun is checked on the results card, and modify table values under the scenario severity.  Observe that the scenario autoruns showing the updated results.

### CODE REVIEW

**Comment by rneher** [comment]
This is great! I am too tired now, but I hope we can push this live tomorrow! Autorun will make exploration of parameters so much smoother!

**Comment by gj262** [comment]
Looks good to me. 

One small nit, changes in the severity table do not auto happen until focus leaves the input. Which is different to the behavior of the population inputs - changes there are reflected as they are typed without leaving the input field. Changing that should probably be another issue.

**Comment by rcbevans** [comment]
You'd want the severity changes to happen on change rather than on blur?

One issue with that, and autorun, is that if the severity table is down where you have to scroll to it, when they results table autoruns, the top of the results card is autoscrolled into view, away from from the severity table.  This is still an issue now when autorun triggers on blur.

**Comment by ivan-aksamentov** [comment]
@rcbevans @gj262 @rneher 
I propose to replace autoscrolling with manually triggered scrolling in #223

**Pull request merged**
