### PR TITLE
Mobile Improvements: Headers markup, popover and text shown

### PR DESCRIPTION
**Pull request by ivnnv**
## Description

Mobile experience needs to be improved and for that goal we also need to cleanup some excessive markup (divs inner divs inner divs that could be simplified):

## Related issues
#71 (Improve mobile experience)

## Impacted Areas in the application
Markup:
Improved markup for CollapsibleHeaders and labels, this make easier to approach improve responsiveness:

*Mitigation Header*
Before:
mitigation big markup

After:
mitigation smaller markup

Composed *Severity Header*:
Before:
combined header big markup

After:
combined header smaller markup

This results on having better alignment of items.

I have also fixed Popover don't being shown on mobile when clicking the HelpLabel, and also made the Popover to hide when the user clicks anywhere outside the popover instead having to click again only in the HelpLabel.

Before:
old-mobile-

After:
Note the previous markup rework now allows the header text to be shown in full -it does now a natural line break:
new-mobile-1

### CODE REVIEW

**Comment by ivan-aksamentov** [comment]
@ivnnv It looks like a useful change, but we are moving fast and now it needs rebase. Plus fixing tests as before. Let me know if you have time and forces for that. Tnanks!

**Comment by ivnnv** [comment]
@ivan-aksamentov sorry I see its getting old, ill try to rebase and update later today!

**Comment by rneher** [comment]
8 days in, can this still be rebased or should we look into picking individuals bits over?

**Comment by ivan-aksamentov** [comment]
It's no longer relevant after new restyling. Closing.

**Pull request closed without merging**
