### PR TITLE
feat: replace range sliders with pairs of spinboxes

### PR DESCRIPTION
**Pull request by ivan-aksamentov**
## Related issues and PRs

 - Contributes to #580 

## Description

This explores the user experience with 
 - a pair of spinboxes as a mean to set ranges of numbers for the parameter uncertainty feature
 - table layout for the mitigation widget

## Impacted Areas in the application

UX

### CODE REVIEW

**Comment by rneher** [comment]
I think this is ultimately easier than the slider. 
 * the allowed ranges should be such that 0<min<max<6 for R0 and 0<min<max<100 for mitigation measures
 * the boxes could be much smaller (with don't expect this to have more than 2-3 digits ever)

**Comment by rneher** [comment]
It looks like @gj262 has also worked on this
https://github.com/gj262/covid19_scenarios/commit/73b1806be86f3b113dacd0682ee4aed732fe9c89

Gavin's solution is actually quite intuitive and allows both single value and range inputs!

**Comment by gj262** [comment]
> It looks like @gj262 has also worked on this
> [gj262@73b1806](https://github.com/gj262/covid19_scenarios/commit/73b1806be86f3b113dacd0682ee4aed732fe9c89)
> 
> Gavin's solution is actually quite intuitive and allows both single value and range inputs!

My change though is still somewhat vaporware. And dealing with long fractional parts e.g.`2.9700000000000006` is easier with dual inputs. (Those long fractional parts are probably bugs but I don't think we want the UI rounding (even though the slider already effectively does that)).

**Comment by ivan-aksamentov** [comment]
@rneher 

 - Is there a particular reason to limit R0 to 6? We did not limit it before, I don't see why limit it now. I typically prefer to avoid "640K ought to be enough for anyone" judgments where possible, because one can never know what are the usecases out there. For example, what if someone wants to show that the values above 6 are not feasible in real life?

 - Boxes are smaller than what you see for most people running on laptop screens. In fact, on some sizes the boxes are too small (barely fitting 2 numbers), so it will probably require some adjustment.

 - Regarding Gavin's solution, it is indeed very pretty, but, as a user, if I would want to get any job done, I would not want that UX: there are no arrow buttons, values have to be typed manually every time. There is a syntactic constraints. For example, if deleted, need to type the " to " keyword in between and/or to precisely aim the mouse cursor to where the number is. It would be an excellent solution for a read-only field, but for the purpose of tweaking and trying different numbers this does not work well in my opinion. Plus it a bit too much of the internal code logic for a very slim gain. Implementing from scratch an input that does not suck is a non-trivial task and there are many examples of failure on npm.

The solution in this PR chooses a way of the least surprise: need to input 2 values - here are the two input boxes, native to the browser. However the semantics of a range still has to be enforced somehow.

For that purpose I was also planning to play with an extended version with adding a slider (so, 2 boxes AND a slider), however I am not sure if I should prioritize another feature instead (e.g. import)

cc @nnoll @noleti what is your opinion on range inputs?

**Comment by noleti** [comment]
My opinion: the spin boxes are better than the sliders (in particular, if we can cut precision to 2 decimals or so). It still seems more effort to use than the old solution for mainstream users. How are the spin boxes planned to be integrated with the auto refresh? A refresh on each cursor button press is maybe too much.

My alternative proposal: One box provides the mean, and the other one the +- delta to the mean. So instead of 2.7 3.3, you would have 3 0.3. The second box could also be the len of the range, i.e. 0.6 in this example. The main intuition is that this allows to shift the mean of R0 easily by modifying one number, instead of having to change 2 all the time. The second input box would essentially configure the range of alternatives to explore.

**Comment by ivan-aksamentov** [comment]
@noleti I was suggesting a `mean ± delta` approach as well, but then scientists said that it looks like a Gaussian. And we draw from uniform. So we kept it as `min - max` for now.

**Pull request merged**
