### PR TITLE
Jittery chart fix

### PR DESCRIPTION
**Pull request by kmid5280**
## Related issues and PRs
Contributes to #234 

## Description
Make tooltip positioning in results chart smoother when mouse is moved over graph.

## Impacted Areas in the application
New throttleDelay value added in ComposedChart component in src/components/Main/Results/DeterministicLinePlot.tsx

## Testing
Move mouse over tooltips in graph and see if desired smoothness is achieved.

### CODE REVIEW

**Comment by kmid5280** [comment]
Some issues that reference general chart jitteriness in this plugin: https://github.com/recharts/recharts/issues/1499 https://github.com/recharts/recharts/issues/1794

**Comment by ivan-aksamentov** [comment]
@kmid5280 Thanks!

I see the difference, I think. It does not jump as much as before. But the difference from master is not huge.

Tooltip still jumps somewhat when you hover and mess around the confirmed cases "dots" (in the bottom-left corner of the plot)

I think we need a deeper dig into the library's docs and its components.
I'd like to also address other points in the issue, so I keep it open.

**Comment by kmid5280** [comment]
@ivan-aksamentov I addressed this issue by setting a value for throttleDelay in the ComposedChart component, line 217. Decreasing that value will decrease the delay, but will increase the jitter if it's too low. So there is likely a happy medium somewhere.

**Comment by leeoniya** [comment]
@ivan-aksamentov @kmid

depending on the types of charts you need, maybe evaluate [uPlot](https://github.com/leeoniya/uPlot) (shameless plug :D)

**Pull request merged**
