### PR TITLE
Change linear interpolation to spline

### PR DESCRIPTION
**Pull request by nnoll**
## Description

The function interpolateTimeSeries has used a linear interpolation that has numerical accuracy problems when attempting to interpolate the mitigation curve onto a different grid. This is exasperated by the fact that we display a spline interpolation.

## Related issues

Issue #187

## Impacted Areas in the application

The fundamental algorithm (which uses an interpolator to estimate the mitigation in between the sampled time points) and the mitigation curve.

## Testing

Needs to be done before I consider this done.

### CODE REVIEW

**Comment by ivan-aksamentov** [comment]
@nnoll Could we use a library for the math? Just to make sure all the tricky corner cases are covered and to not maintain yet another library of matrix operations. We've removed `math.js` because it was not used, should we bring it back?

**Comment by ivan-aksamentov** [comment]
Someone needs to help Nick with testing the new algorithm

**Comment by abrie** [comment]
I'd like to help.

As expected, these changes break existing unit tests:

- TimeSeries.test.tsx:interpolateTimeSeries()
- model.test.ts:evolve()

Fixing those tests is simply a matter of updating the output snapshots.

In addition, there should be need a new test to verify that the new algorithm yields results expected by issue #187. I have a naive understanding of the problem, but maybe the test could be:

1. Run the model for one time series, and save the output.
2. Adjust the time series to be longer, run the model again, save the output.
3. Compare the two outputs, and verify that overlapping dates have the same values.

**Comment by rneher** [comment]
My exploration of the result look sensible. reducing the length of the simulation gives the same dynamics as far as I can tell. This could be used as test: 
  
   * run a time series and save at mid-time
   * shrink the time series and compare results at the same time point.

Increasing the length of the time series is not ideal since the spline interpolation then extends into time ranges that weren't previously covered. Since splines are not strictly local, this can change the results also within the time range that was previously simulated. 

Another point that is worth considering is that we need to guard against negative values. 

image

I generated this by dragging two adjacent points to zero and then changing the number of points. 

An alternative fix for this would be to stick to the linear interpolation, interpolate the graph by lines instead of splines, and don't drop points when changing the time interval. This would generate messy graphs with different intervals and it is unclear what to do with the `number of points` box. But I am hesitant to sink too much effort into this as we plan to change this component soon.

**Comment by nnoll** [comment]
@rneher regarding the extrapolation onto a larger date range - I kept the same basic logic as our previous linear interpolation, which is if we are asked to extrapolate beyond our current date range, then set it to the last value of the range. Is this not what you observe when you extend the date range?

I just pushed a fix to updateTimeSeries that guards against negative containment values.

**Comment by nnoll** [comment]
OK I now use mathjs to perform the gauss jordan elimination.

**Comment by ivan-aksamentov** [comment]
@nnoll I merged master into it and fixed tests (sort of)
This this ready?

**Comment by nnoll** [comment]
@Ivan Yes, I haven't been able to break it yet and if we find an issue in deployment I'll fix it. I think merge when you can

**Pull request merged**
