### PR TITLE
feat: "Run in new tab" button

### PR DESCRIPTION
**Pull request by dkozar**
image

Video: https://microsofteur-my.sharepoint.com/:v:/g/personal/dakozar_microsoft_com/EUJfeLgUXUlGnyydA2_13PQBEx_yzjhMNA0PCnC37bDxlw?e=Wab9iF

## Related issues and PRs

Issues:
- https://github.com/neherlab/covid19_scenarios/issues/346
- https://github.com/neherlab/covid19_scenarios/issues/284
- https://github.com/neherlab/covid19_scenarios/issues/358
- https://github.com/neherlab/covid19_scenarios/issues/181
- https://github.com/neherlab/covid19_scenarios/issues/31

PRs:
- https://github.com/neherlab/covid19_scenarios/pull/329
- https://github.com/neherlab/covid19_scenarios/pull/366

## Description

This PR adds a button which opens and runs the scenario in another browser tab.
## Impacted Areas in the application

ResultsCard

## Testing

Set scenario parameters and click the "Run in new tab" button. The app will open in new tab, with scenario parameters being transferred via the URL. The scenario will run automatically and the graphs will be shown.

Additionally, whenever the user loads the app, during its initialization the URL is checked. If it contains query, the query is parsed and the scenario is run. This is handy (and expected) when the link was shared via email etc.

### CODE REVIEW

**Comment by dkozar** [comment]
The feature could be checked here: https://covid19-scenarios-cfau3dmod.now.sh/

As said, if the shared contains query string and is clicked, the graphs will automatically be rendered. For instance, [this link](https://covid19-scenarios-cfau3dmod.now.sh/?%7B%22population%22%3A%7B%22ICUBeds%22%3A650%2C%22cases%22%3A%22Croatia%22%2C%22country%22%3A%22Croatia%22%2C%22hospitalBeds%22%3A16974%2C%22importsPerDay%22%3A0.6%2C%22populationServed%22%3A4105000%2C%22suspectedCasesToday%22%3A0%7D%2C%22epidemiological%22%3A%7B%22infectiousPeriod%22%3A3%2C%22latencyTime%22%3A3%2C%22lengthHospitalStay%22%3A4%2C%22lengthICUStay%22%3A14%2C%22overflowSeverity%22%3A2%2C%22peakMonth%22%3A0%2C%22r0%22%3A2.1%2C%22seasonalForcing%22%3A0%7D%2C%22simulation%22%3A%7B%22simulationTimeRange%22%3A%7B%22tMin%22%3A%222020-02-21T00%3A00%3A00.000Z%22%2C%22tMax%22%3A%222020-09-01T00%3A00%3A00.000Z%22%7D%2C%22numberStochasticRuns%22%3A0%7D%2C%22containment%22%3A%5B%7B%22t%22%3A%222020-02-21T00%3A00%3A00.000Z%22%2C%22y%22%3A1%7D%2C%7B%22t%22%3A%222020-03-05T18%3A51%3A25.714Z%22%2C%22y%22%3A1%7D%2C%7B%22t%22%3A%222020-03-19T13%3A42%3A51.428Z%22%2C%22y%22%3A1%7D%2C%7B%22t%22%3A%222020-04-02T08%3A34%3A17.142Z%22%2C%22y%22%3A0.7142857142857143%7D%2C%7B%22t%22%3A%222020-04-16T03%3A25%3A42.857Z%22%2C%22y%22%3A0.7142857142857143%7D%2C%7B%22t%22%3A%222020-04-29T22%3A17%3A08.571Z%22%2C%22y%22%3A0.7142857142857143%7D%2C%7B%22t%22%3A%222020-05-13T17%3A08%3A34.285Z%22%2C%22y%22%3A0.7142857142857143%7D%2C%7B%22t%22%3A%222020-05-27T12%3A00%3A00.000Z%22%2C%22y%22%3A0.7142857142857143%7D%2C%7B%22t%22%3A%222020-06-10T06%3A51%3A25.714Z%22%2C%22y%22%3A0.7142857142857143%7D%2C%7B%22t%22%3A%222020-06-24T01%3A42%3A51.428Z%22%2C%22y%22%3A0.7142857142857143%7D%2C%7B%22t%22%3A%222020-07-07T20%3A34%3A17.142Z%22%2C%22y%22%3A0.7142857142857143%7D%2C%7B%22t%22%3A%222020-07-21T15%3A25%3A42.857Z%22%2C%22y%22%3A0.7142857142857143%7D%2C%7B%22t%22%3A%222020-08-04T10%3A17%3A08.571Z%22%2C%22y%22%3A0.7142857142857143%7D%2C%7B%22t%22%3A%222020-08-18T05%3A08%3A34.285Z%22%2C%22y%22%3A0.7142857142857143%7D%2C%7B%22t%22%3A%222020-09-01T00%3A00%3A00.000Z%22%2C%22y%22%3A0.7142857142857143%7D%5D%2C%22current%22%3A%22Croatia%22%7D).

**Comment by dkozar** [comment]
@ivan-aksamentov @rneher could you take a look, and possibly merge? 😃

**Comment by dkozar** [comment]
@ivan-aksamentov @rneher since https://github.com/neherlab/covid19_scenarios/pull/372 has been merged, this works fine now.

Demo: https://covid19-scenarios-6z8tnp2jj.now.sh/

Also, let me pass the scenario (state) within a query string, for you to try - [here's it is](https://covid19-scenarios-6z8tnp2jj.now.sh/?%7B%22population%22%3A%7B%22ICUBeds%22%3A650%2C%22cases%22%3A%22Croatia%22%2C%22country%22%3A%22Croatia%22%2C%22hospitalBeds%22%3A16974%2C%22importsPerDay%22%3A0.1%2C%22populationServed%22%3A4105000%2C%22suspectedCasesToday%22%3A4%7D%2C%22epidemiological%22%3A%7B%22infectiousPeriod%22%3A3%2C%22latencyTime%22%3A3%2C%22lengthHospitalStay%22%3A4%2C%22lengthICUStay%22%3A14%2C%22overflowSeverity%22%3A2%2C%22peakMonth%22%3A0%2C%22r0%22%3A2.6%2C%22seasonalForcing%22%3A0%7D%2C%22simulation%22%3A%7B%22simulationTimeRange%22%3A%7B%22tMin%22%3A%222020-02-21T00%3A00%3A00.000Z%22%2C%22tMax%22%3A%222020-09-01T00%3A00%3A00.000Z%22%7D%2C%22numberStochasticRuns%22%3A0%7D%2C%22containment%22%3A%5B%7B%22t%22%3A%222020-02-21T00%3A00%3A00.000Z%22%2C%22y%22%3A1%7D%2C%7B%22t%22%3A%222020-03-05T18%3A51%3A25.714Z%22%2C%22y%22%3A1%7D%2C%7B%22t%22%3A%222020-03-19T13%3A42%3A51.428Z%22%2C%22y%22%3A1%7D%2C%7B%22t%22%3A%222020-04-02T08%3A34%3A17.142Z%22%2C%22y%22%3A1%7D%2C%7B%22t%22%3A%222020-04-16T03%3A25%3A42.857Z%22%2C%22y%22%3A1%7D%2C%7B%22t%22%3A%222020-04-29T22%3A17%3A08.571Z%22%2C%22y%22%3A1%7D%2C%7B%22t%22%3A%222020-05-13T17%3A08%3A34.285Z%22%2C%22y%22%3A1%7D%2C%7B%22t%22%3A%222020-05-27T12%3A00%3A00.000Z%22%2C%22y%22%3A1%7D%2C%7B%22t%22%3A%222020-06-10T06%3A51%3A25.714Z%22%2C%22y%22%3A1%7D%2C%7B%22t%22%3A%222020-06-24T01%3A42%3A51.428Z%22%2C%22y%22%3A1%7D%2C%7B%22t%22%3A%222020-07-07T20%3A34%3A17.142Z%22%2C%22y%22%3A1%7D%2C%7B%22t%22%3A%222020-07-21T15%3A25%3A42.857Z%22%2C%22y%22%3A1%7D%2C%7B%22t%22%3A%222020-08-04T10%3A17%3A08.571Z%22%2C%22y%22%3A1%7D%2C%7B%22t%22%3A%222020-08-18T05%3A08%3A34.285Z%22%2C%22y%22%3A1%7D%2C%7B%22t%22%3A%222020-09-01T00%3A00%3A00.000Z%22%2C%22y%22%3A1%7D%5D%2C%22current%22%3A%22Croatia%22%7D) (you should see Croatia selected).

Could we merge this?

**Comment by nnoll** [comment]
This looks great to me. I'll let @ivan-aksamentov have the final say.

**Comment by gj262** [comment]
Hey @dkozar this has introduced a react error in the latest master. Can you take a look?

Screen Shot 2020-04-03 at 10 42 29 PM

**Comment by dkozar** [comment]
Taking a look..

**Comment by ivan-aksamentov** [comment]
@gj262 @dkozar You probably figured this already, but this is a warning from `prop-types` which are auto generated from typescript types:

https://github.com/neherlab/covid19_scenarios/blob/2498f1e357590beb159eb8ed8a49a324e9ed1f3b/babel.config.js#L44

So you just need to either change the typing or to make sure that it's honored everywhere.
We've fixed almost all linting issues in the codebase, so should be able to enable type checking and linting during build soon, to catch these earlier.

**Comment by dkozar** [comment]
That's fine, we should have these checks in place. I introduced the problem by mistake.

Fix: https://github.com/neherlab/covid19_scenarios/pull/401

**Pull request merged**
