### PR TITLE
Additional PDF Details

### PR DESCRIPTION
**Pull request by nspringman**
## Related issues and PRs

 - Related to #488 

## Description

Fixed some of the existing short descriptions as well as adding a few longer descriptions in the form of footnotes. Copied long descriptions from homepage help text as to not cause any translation issues. Are there other notes or descriptions that need to be added? And is the footnote style the direction you want to go, or would another format be better? 
## Impacted Areas in the application

PrintPreview.tsx

### CODE REVIEW

**Comment by ivan-aksamentov** [comment]
@nspringman Thanks! LGTM.

The idea of #488 was more like on a scientific side, to improve content of the document as a whole (layout, informativeness, readability). This is a job for a domain expert. Back then we only applied a few cosmetic fixes and kinda abandoned that issue.

Anyways, your cleanup is welcome.

I will let @rneher to double check and merge.

**Comment by rneher** [comment]
Looks great to me. I like the superscript explanations for the pdf/print version!

**Comment by rneher** [comment]
you had it labeled as draft, did you want to add more? If not, I'll merge it....

**Comment by nspringman** [comment]
If there are other parameters in that list you think should have a longer description, I can certainly go ahead and add those. We had just selected the few that seemed most likely to warrant another note. Otherwise, if all looks okay with you, good to merge!

**Comment by ivan-aksamentov** [comment]
@nspringman Done, thanks!

**Pull request merged**
