### PR TITLE
Layout improvement faq team

### PR DESCRIPTION
**Pull request by kimuraz**
## Related issues and PRs

Contributes to #148

## Description
This PR includes several commits changing the team (now acknowledgements) and FAQ pages.

## Impacted Areas in the application
- Navbar
- Team
- FAQ
- routes
- links

## Testing
UI checking

### CODE REVIEW

**Comment by kimuraz** [comment]
> @kimuraz Thanks!
> 
> Few notes:
> 
> * [ ]  You don't need `react-markdown` package and to load and parse .md file on runtime. First of all it can be done on build-time. Second, loading files from GitHub and relying on their content is not going to work for us. What if someone change the README.md? The website would not render the page correctly.
> * [ ]  Gladly, there is a better approach. As I mentioned in the issue, we are using mdx.js and you can just import the .md file as a component. This way it becomes a part of the website bundle, just like any other React component. See for example `src/pages/About.mdx` (this is .mdx file, but it does not matter, you can import into .tsx files too).
> * [ ]  If you need to customize the imported component, you can pass custom components to override the defaults. See mdx.js docs ["Working with components"](https://mdxjs.com/getting-started#working-with-components)
> * [ ]  If needed, you can make a copy of the "Initial development" section of the REAMDEmd in a separate file, for example `src/assets/text/initial-development.md` and then import it. It will still be a duplicate, but at least when README.md is updated I can just copy-paste the update into `initial-development.md` and rebuild.

Thanks for the feedaback, I didn't realise the usage of the library on this way, but will replace it. My first though was to get the content from README during runtime because then it can be maintained in a single place, but of course the mdx will also fix it.

**Comment by ivan-aksamentov** [comment]
@kimuraz  I understand your point about single place. duplicating is bad. However this content is unlikely to change, so it's okay.

**Comment by ivan-aksamentov** [comment]
@kimuraz This is looking really good! Styling is a bit off here and there, but this is expected with markdown. It can be fixed later. Let me know when you are happy with the result and we can merge that.

**Comment by kimuraz** [comment]
@ivan-aksamentov sure, thanks for reviewing, I'll do some more work on the contributors, I think it can be improved before, then I'll check lints and tests. I'll do it today evening.

**Comment by kimuraz** [comment]
@ivan-aksamentov There are some issues on the CI but I saw there's a PR fixing them, once if it's merged before this one, I can rebase it.

**Comment by kimuraz** [comment]
Rebased and passing the checks 👍

**Pull request merged**
