### PR TITLE
Issue 56: German Translation

### PR DESCRIPTION
**Pull request by FireLizard**
## Description

Adds German translation

## Related issues

https://github.com/neherlab/covid19_scenarios/issues/56

### CODE REVIEW

**Comment by ivan-aksamentov** [comment]
Hi @FireLizard ,
This PR is marked as draft, so I cannot merge it. Are you planning to continue? We can merge incrementally to make sure there are no conflicting PRs or duplicated work done by someone else.
Let me know how you want to proceed or if you need anything.

**Comment by FireLizard** [comment]
Hi @ivan-aksamentov ,
I would rebase onto https://github.com/neherlab/covid19_scenarios/pull/85 and start translating the existing keys.

Do we already have a good practice to include locale external links? For example on [Team.tsx](https://github.com/neherlab/covid19_scenarios/blob/master/src/pages/Team.tsx) "research group"  is wrapped by `LinkExternal`. It would make sense to translate the URI in case of a localized target, wouldn't it?

**Comment by ivan-aksamentov** [comment]
@FireLizard sounds like a plan.

We don't have a practice established. Feel free to establish :)
In this case, also add something to the README in dev section. Don't worry if it will be hanging alone there, we will gather all the bits later into a cohesive guide.

**Comment by ivan-aksamentov** [comment]
@FireLizard I merged #85 , feel free to jump in

**Comment by FireLizard** [comment]
I have completed the german translation so far (rebased onto #85).

Some errors occur due to missing translations of json files in `./src/assets/data/`. For example when choosing the preset scenario "Country - no mitigation" it shows **Error: population scenario "Deutschland" not found** (posted it also in #56 for discussing)

**Pull request merged**
