### PR TITLE
issue #134: use an UncontrolledPopover to fix popovers for Safari

### PR DESCRIPTION
**Pull request by gj262**
## Description

Help information would not display for Safari users.

## Related issues

Fixes https://github.com/neherlab/covid19_scenarios/issues/134

## Impacted Areas in the application

Help Popovers.

## Testing

- Tested with Chrome & Safari on MacOS
- Changed the help popover unit test to use clicks

## Deploy Notes

None

### CODE REVIEW

**Comment by gj262** [comment]
This is a bizarre CI failure given that the `popoverOpen` variable is gone now...

**Comment by ivan-aksamentov** [comment]
Indeed, local tests pass.

Do you see anything immediately wrong with the travis setup:
https://github.com/neherlab/covid19_scenarios/blob/master/.travis.yml
?

**Comment by ivan-aksamentov** [comment]
@gj262 I disabled and cleared the cache. Could you please rebase on master to see if it helps?

**Comment by gj262** [comment]
hmmm, I seem to have made a git mess :( And it is still not working for the same error. I'm gonna try a new branch and then give up  for the night :)

**Pull request closed without merging**
