### PR TITLE
Drag/Resize Scenario and Results vs. Zoom in/out chart

### PR DESCRIPTION
**Pull request by guandiyiyi**
## Related issues and PRs
"Expand" the results panel
#284
 - 

## Description
Allow drag and resize the left and right panel
working in progress to allow zoom in/out

## Impacted Areas in the application
Main page: Scenario card and Results card

### CODE REVIEW

**Comment by rneher** [comment]
Thanks. Being able to zoom the graph is nice. I am struggling a bit with the discoverability of this zooming. Currently, clicking and dragging zooms but without any feedback to the user, this is almost a little surprising. Could one add a highlight like this:
http://recharts.org/en-US/examples/HighlightAndZoomLineChart

**Comment by guandiyiyi** [comment]
Yup, I agree. Original I added a reference area, but after pull the latest change, it's conflicting with the newly added mitigation strength reference area :(.....I will try to play around a bit today to sort out a solution

**Comment by guandiyiyi** [comment]
> Thanks. Being able to zoom the graph is nice. I am struggling a bit with the discoverability of this zooming. Currently, clicking and dragging zooms but without any feedback to the user, this is almost a little surprising. Could one add a highlight like this:
> http://recharts.org/en-US/examples/HighlightAndZoomLineChart

Yup, I agree. Original I added a reference area when click, but after pull the latest change, it's conflicting with the newly added mitigation strength reference area :(.....I will try to play around a bit today to sort out a solution

**Comment by guandiyiyi** [comment]
> Thanks. Being able to zoom the graph is nice. I am struggling a bit with the discoverability of this zooming. Currently, clicking and dragging zooms but without any feedback to the user, this is almost a little surprising. Could one add a highlight like this:
> http://recharts.org/en-US/examples/HighlightAndZoomLineChart

@rneher added reference area now, please check, thanks for review.

**Comment by rneher** [comment]
The reference area is good. It is a little laggy for me probably because it is trying to rerender the tooltip all the time. I am not a fan of the zooming on click. It seems unexpected to me. Also the mitigation boxes are gone after zoom. the style of the zoom out button could be improved. But I think it is almost there.

**Comment by guandiyiyi** [comment]
> The reference area is good. It is a little laggy for me probably because it is trying to rerender the tooltip all the time. I am not a fan of the zooming on click. It seems unexpected to me. Also the mitigation boxes are gone after zoom. the style of the zoom out button could be improved. But I think it is almost there.

good catch for these bugs, commit new changes to fix:
1. align the button styles with the other buttons on the page
2. avoid zoom when click
3.  add mitigation boxes when zoom

**Comment by guandiyiyi** [comment]
> > The reference area is good. It is a little laggy for me probably because it is trying to rerender the tooltip all the time. I am not a fan of the zooming on click. It seems unexpected to me. Also the mitigation boxes are gone after zoom. the style of the zoom out button could be improved. But I think it is almost there.
> 
> good catch for these bugs, commit new changes to fix:
> 
> 1. align the button styles with the other buttons on the page
> 2. avoid zoom when click
> 3. add mitigation boxes when zoom



> Yes, this is very useful now!

thanks, merged :)

**Pull request merged**
