### PR TITLE
add progress indicator to the result section

### PR DESCRIPTION
**Pull request by Chong-anson**
## Related issues and PRs

 - add progress indicator to the result section #688 

## Description

 - create a spinner when the plot is loading. The spinner is aligned with the indicator to the button.

## Impacted Areas in the application

 - add PlotSpinner component which renders the spinner logo. 
 - add ternary logic to the plot components so that when the result "isRunning", it will render the spinner icon. Otherwise, it will the normal components
 - edit result css file to centre the spinner icon

### CODE REVIEW

**Comment by ivan-aksamentov** [comment]
@Chong-anson Thanks, it looks promising, however I insist on this important feature (from the original issue):

>  - should not obscure the plot completely, such that the moment when changes arrive can be seen

The whole idea of the app is to allow user to explore different parameters and to see how they affect the results (for example, when relaxing the quarantine measures, death plot goes up, etc.) 
In this PR, when loading indicator is shown, the plot disappears and the entire results section changes its layout. This makes it difficult to track the changes visually when changing parameters. 

Instead of conditional rendering (spinner vs plot) we could implement a semi-transparent overlay on top of the plot, such that the data and the transition from one result to another is visible at all times.

Note, that rendering the whole plot from scratch is very costly (takes from 500 to 1000ms on average machine), so we want to ensure that only the changed items are re-rendered (for example, axes, grid and legend stays the same). This means that we need to avoid unmounting the plot component, changing it's size and changing its props unnecessarily.

Also, currently, the size is changing when switching between the spinner and the plot. Implementing overlay should hopefully fix that. Additional bonus for ensuring  that there is no size jump on first render (you know, when the results section "unrolls" down on app load).

This is a creative issue, so feel free to experiment, implement your own idea of how it may look like and refactor the code structure when needed.

**Comment by Chong-anson** [comment]
Thanks for your detailed comment! I will work on that!

**Comment by Chong-anson** [comment]
Hi Ivan, I edited the components in ResultCard and added some CSS. Sorry for the delay, my internet was down. Currently working on the "unrolling issue" in the first render.

**Comment by ivan-aksamentov** [comment]
This looks good thanks!
Resolves #688

**Pull request merged**
