### PR TITLE
feat: add autorun toggle

### PR DESCRIPTION
**Pull request by 3b3ziz**
## Description
This pull request implements the autorun feature based on the values object provided by formik.

## Related issues
Fixes https://github.com/neherlab/covid19_scenarios/issues/17

### CODE REVIEW

**Comment by ivan-aksamentov** [comment]
Hi @3b3ziz thanks for the efforts!

Unfortunately this makes the for too slow. For example, if I go to the deployed version:
https://covid19-scenarios-git-fork-3b3ziz-feat-autorun-onchange.covid19-scenarios.now.sh/
and try to increase the population with arrows or to type in any numeric field, the entire apo hangs for a second or two after every click or key stroke. We cannot allow this kind of user experience.

I have a branch, where I tried to implement this and also revamped the whole state and state updates in Redux. Bit it is unfinished and it's a bit of a mess, but maybe you'll find something useful useful.
https://github.com/neherlab/covid19_scenarios/compare/feat/autorun

Another minor thing is that we want to autorun the algorithm on app startup as well.

I hope you can fix the freezes. That would be fantastic!

**Comment by 3b3ziz** [comment]
@ivan-aksamentov Could you please check again the speed of the deployed version now? https://covid19-scenarios-git-fork-3b3ziz-feat-autorun-onchange.covid19-scenarios.now.sh/

I have used a different (Supposedly more efficient) approach and also added the autorun to work on app startup.

Generally, I think there is a performance problem since I noticed that the app renders multiple times when changing input fields. I will try to investigate in that as well.

**Comment by ivan-aksamentov** [comment]
@3b3ziz I did not notice any changes, it still freezes. 
Repro: try to delete the number in "Populations" field and then quickly (within 1 second) to enter "123456789". It takes  about 5-7 seconds before the UI get responsive again. I suspect that the algorithm runs 10 times or so, after every keystroke.

**Comment by ivan-aksamentov** [comment]
@3b3ziz it is a hard problem with the current setup. That is why I haven't solved it yet. And nobody else seem to be taking it. I am very happy that you are still trying. I believe we van crack it sometimes :)

**Comment by rneher** [comment]
It actually runs fairly ok on my machine. Could one make it rerender only when one leaves field through enter or tab or similar? Or wait 2s before rerendering. It doesn't update when dragging the mitigation graph. 

In general, I am big fan of autorun!

**Comment by rcbevans** [comment]
Haven't taken a look at your implementation, but I would suggest taking a look at lodash's [debounce](https://lodash.com/docs#debounce) functionality with perhaps a 2s delay, reset on each input form value change.

**Comment by ivan-aksamentov** [comment]
@3b3ziz Hi Ahmad, in the end I've merged an alternative solution in #170. But thanks for your attempt and investigation! If there is something else we need to carry from your branch, feel free to open another PR.

**Pull request closed without merging**
