### PR TITLE
Change model results to percentiles over geometric mean/standard deviation

### PR DESCRIPTION
**Pull request by nnoll**
## Related issues and PRs

 - 

## Description

The geometric mean and standard deviation led to odd visual results. 
We now will report percentiles over time.

## Impacted Areas in the application

model.ts
run.ts
Changed userResult.trajectory.mean -> userResult.trajectory.middle

## Testing

Check model plots and exports with new data structure.

### CODE REVIEW

**Comment by nnoll** [comment]
@rneher @ivan-aksamentov @noleti: I'm unsure about the notation for median & lower/upper percentiles. Thoughts here?

**Comment by ivan-aksamentov** [comment]
I thought you mentioned a tuple/triplet, for example:

lower, **median**, upper
2.78, **3.14**, 6.28

**Comment by noleti** [comment]
For USA without mitigations, ICU looks good now, but overflow median does not start at 0. I think it didn't before either, I just noticed. Otherwise this looks good. I'm not sure why you call it percentiles here, that just applies if we assume the input range is some distribution, no? The lower, median, upper values plotted are deterministic, no?
icuCap2

**Comment by nnoll** [comment]
@ivan-aksamentov my original thoughts were to do a tuple. I ended up on this after some trial and error but am not wedded to the UX at all.

@noleti the input parameters are ranges now for R0 & mitigation efficacy. You are adjusting the prior distributions (which are assumed uniform) when you play with the slider hence the percentile. I agree that the help buttons text should be updated to reflect this.

**Comment by nnoll** [comment]
@ivan-aksamentov my original thoughts were to do a tuple. I ended up on this after some trial and error but am not wedded to the UX at all.

@noleti the input parameters are ranges now for R0 & mitigation efficacy. You are adjusting the prior distributions (which are assumed uniform) when you play with the slider hence the percentile. I agree that the help buttons text should be updated to reflect this.

**Comment by rneher** [comment]
Ideally one would have something like 
"2020-04-20   (10%, median 90%)"
the title of the tool tip and then numbers as a tuple. The current colon notation is a little odd. I like Ivan's proposal with the bold median.

**Pull request merged**
