### PR TITLE
Apply viewport height to spinner style

### PR DESCRIPTION
**Pull request by kmid5280**
## Related issues and PRs
#442 
 - 

## Description
Change margin-top value in spinner to use viewport height instead of straight percentage. Should achieve better centering.

## Impacted Areas in the application
Loading.scss

## Testing
Refresh main page to see spinner.

### CODE REVIEW

**Comment by kmid5280** [comment]
@dkozar I tried implementing your suggestions here. Let me know how it looks.

**Comment by dkozar** [comment]
Thanks for the effort!

The spinner was still not centered. I took a look, and the parent was causing some problems. Here are the two solutions:

1. The "calc" solution

```css
.loading-page {
  position: fixed;
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;

  > div.spinner-border {
    margin-top: calc((100vh - 6rem) / 2);
    width: 6rem;
    height: 6rem;
    animation-duration: 1.5s;
  }
}
```

2. "flexbox" solution

```css
.loading-page {
  position: fixed;
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
  display: flex;
  flex-direction: column;
  align-items: center;

  > div.spinner-border {
    width: 6rem;
    height: 6rem;
    animation-duration: 1.5s;
  }
}
```

Let's go with the 2nd one, because it seems superior - spinner size is defined in one place only, and also, if another element is _eventually_ added below, the whole section will remain centered:

Snag_b2ba8b1

Snag_b2bc801

**Comment by dkozar** [comment]
@kmid5280 thanks! I created another PR here: https://github.com/neherlab/covid19_scenarios/pull/482 (wasn't able to get merge with your branch).

**Comment by ivan-aksamentov** [comment]
Closing in favor of #482

**Pull request closed without merging**
