### PR TITLE
Update initial values for Ukraine

### PR DESCRIPTION
**Pull request by Vanuan**
https://web.archive.org/web/20200328082145/https://moz.gov.ua/article/news/operativna-informacija-pro-poshirennja-koronavirusnoi-infekcii-2019-ncov-

### CODE REVIEW

**Comment by noleti** [comment]
I am pretty sure `data/initialCondition.tsv ` is not actually used any more, as the model.py now fits such values based on observations. I leave this to others to close (and possibly delete the `data/initialCondition.tsv `). @nnoll ?

**Comment by Vanuan** [comment]
@noleti Why Ukraine doesn't show up in the dropdown then?

**Comment by nnoll** [comment]
@noleti @Vanuan  It is used, however it is generated from fitting case count data to our model. Ukraine will be available from our dropdown once we re-run our initial condition estimates!

**Comment by Vanuan** [comment]
@nnoll Could you update it please? Do you want me to run and send a PR?

**Comment by nnoll** [comment]
@vanuan. I can rerun the fits tonight. If you can and are willing to get to it sooner, please do!

**Comment by nnoll** [comment]
Hey @Vanuan. I wasn't able to get to this tonight, but I promise tomorrow I will upload a PR with the fit data. Sorry for the delay.

**Comment by nnoll** [comment]
OK. I've fit and included Ukraine with #556 so I'll close this. Feel free to open an issue if there's anything else! Thanks for your contribution.

**Pull request closed without merging**
